---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trivy-scan
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Security
    tekton.dev/tags: CLI, trivy
    tekton.dev/displayName: "trivy scanner"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    Trivy is a simple and comprehensive scanner for
    vulnerabilities in container images,file systems
    ,and Git repositories, as well as for configuration issues.

    This task can be used to scan for vulnenrabilities on the source code
    in stand alone mode.
  workspaces:
    - name: manifest-dir
  params:
    - name: ARGS
      description: The Arguments to be passed to Trivy command.
      type: string
      default: "image --exit-code 0"
    - name: TRIVY_IMAGE
      default: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/devops/aquasec/trivy:v0.2
      description: Trivy scanner image to be used
    - name: IMAGE
      description: Image or Path to be scanned by trivy.
    - name: AIR_GAPPED_ENABLED
      default: "true"
      description: a flag enabling Air-Gapped mode
      type: string
  steps:
    - name: trivy-scan
      image: $(params.TRIVY_IMAGE)
      workingDir: $(workspaces.manifest-dir.path)
      script: |
        #!/usr/bin/env sh
          cmd="trivy $* "
          if [ "$(params.AIR_GAPPED_ENABLED)" = "true" ]; then
            echo "Air-Gapped mode enabled"
            TRIVY_TEMP_DIR=$(mktemp -d)
            trivy --cache-dir $TRIVY_TEMP_DIR image --download-db-only
            tar -cf ./db.tar.gz -C $TRIVY_TEMP_DIR/db metadata.json trivy.db
            rm -rf $TRIVY_TEMP_DIR
            mkdir -p $HOME/.cache/trivy/db
            tar xvf ./db.tar.gz -C $HOME/.cache/trivy/db
            cmd+="--skip-update "
          fi
          echo "Running trivy task with command below"
          echo "$cmd"
          eval "$cmd"
      args:
        - "$(params.ARGS) $(params.IMAGE)"
